import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'rtl' | 'ltr';
}

const translations: Record<Language, Record<string, string>> = {
  ar: {
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.surveys': 'الاستبيانات',
    'nav.complaints': 'الشكاوى',
    'nav.recommendations': 'التوصيات',
    'nav.archives': 'الأرشيف',
    'nav.comparison': 'مقارنة البرامج',
    'nav.users': 'المستخدمون',
    'nav.settings': 'الإعدادات',
    'nav.logout': 'تسجيل الخروج',
    'nav.home': 'الصفحة الرئيسية',
    
    // Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.welcome': 'مرحباً بك في نظام إدارة الاستبيانات',
    'dashboard.welcomeUser': 'مرحباً',
    'dashboard.systemTitle': 'منظومة الاستبيانات الذكية',
    'dashboard.totalSurveys': 'إجمالي الاستبيانات',
    'dashboard.activeSurveys': 'الاستبيانات النشطة',
    'dashboard.totalResponses': 'إجمالي الاستجابات',
    'dashboard.responseRate': 'معدل الاستجابة',
    'dashboard.readyReports': 'التقارير الجاهزة',
    'dashboard.pendingComplaints': 'الشكاوى المعلقة',
    'dashboard.recentActivity': 'النشاط الأخير',
    'dashboard.recentSurveys': 'الاستبيانات الأخيرة',
    'dashboard.recentSurveysDesc': 'الاستبيانات النشطة وحالة الاستجابات',
    'dashboard.quickActions': 'الإجراءات السريعة',
    'dashboard.createSurvey': 'إنشاء استبيان جديد',
    'dashboard.newSurvey': 'استبيان جديد',
    'dashboard.viewReports': 'عرض التقارير',
    'dashboard.viewReport': 'عرض التقرير',
    'dashboard.manageComplaints': 'إدارة الشكاوى',
    'dashboard.manageSurveys': 'إدارة الاستبيانات',
    'dashboard.noSurveys': 'لا توجد استبيانات حالياً',
    'dashboard.viewAllSurveys': 'عرض جميع الاستبيانات',
    'dashboard.followRecommendations': 'متابعة التوصيات',
    'dashboard.semesterArchive': 'الأرشيف الفصلي',
    'dashboard.manageUsers': 'إدارة المستخدمين',
    'dashboard.systemSettings': 'إعدادات النظام',
    'dashboard.response': 'استجابة',
    
    // Surveys
    'surveys.title': 'إدارة الاستبيانات',
    'surveys.subtitle': 'عرض وإدارة الاستبيانات والنماذج',
    'surveys.create': 'إنشاء استبيان',
    'surveys.edit': 'تعديل',
    'surveys.delete': 'حذف',
    'surveys.view': 'عرض',
    'surveys.status': 'الحالة',
    'surveys.responses': 'الردود',
    'surveys.actions': 'الإجراءات',
    'surveys.draft': 'مسودة',
    'surveys.active': 'نشط',
    'surveys.closed': 'مغلق',
    'surveys.noSurveys': 'لا توجد استبيانات',
    'surveys.createFirst': 'إنشاء أول استبيان',
    'surveys.newSurvey': 'استبيان جديد',
    'surveys.templates': 'النماذج',
    'surveys.updateQR': 'تحديث رموز QR',
    'surveys.searchPlaceholder': 'البحث في الاستبيانات...',
    'surveys.activate': 'تفعيل',
    'surveys.deactivate': 'إيقاف',
    'surveys.link': 'رابط',
    'surveys.report': 'التقرير',
    'surveys.program': 'برنامج',
    'surveys.noTemplates': 'لا توجد نماذج محفوظة',
    'surveys.createAndSaveTemplate': 'إنشاء استبيان وحفظه كنموذج',
    'surveys.public': 'عام',
    'surveys.useTemplate': 'استخدام',
    
    // Complaints
    'complaints.title': 'إدارة الشكاوى',
    'complaints.subtitle': 'متابعة ومعالجة شكاوى الطلاب والموظفين',
    'complaints.submit': 'تقديم شكوى',
    'complaints.submitNew': 'شكوى جديدة',
    'complaints.status': 'الحالة',
    'complaints.pending': 'قيد المراجعة',
    'complaints.inProgress': 'قيد المعالجة',
    'complaints.resolved': 'تم الحل',
    'complaints.closed': 'مغلقة',
    'complaints.subject': 'الموضوع',
    'complaints.description': 'الوصف',
    'complaints.type': 'النوع',
    'complaints.date': 'التاريخ',
    'complaints.total': 'إجمالي الشكاوى',
    'complaints.submitComplaint': 'تقديم شكوى',
    'complaints.submitTitle': 'تقديم شكوى',
    'complaints.submitSubtitle': 'نحن هنا للاستماع إلى ملاحظاتك وشكاواك',
    'complaints.formTitle': 'نموذج الشكوى',
    'complaints.formSubtitle': 'يرجى ملء جميع الحقول المطلوبة (*)',
    'complaints.confidentialNote': 'جميع الشكاوى يتم معالجتها بسرية تامة. يرجى تقديم معلومات دقيقة لمساعدتنا في حل المشكلة بأسرع وقت ممكن.',
    'complaints.personalInfo': 'المعلومات الشخصية',
    'complaints.fullName': 'الاسم الكامل',
    'complaints.email': 'البريد الإلكتروني',
    'complaints.academicId': 'الرقم الأكاديمي / الوظيفي',
    'complaints.complainantType': 'نوع المشتكي',
    'complaints.student': 'طالب',
    'complaints.faculty': 'عضو هيئة تدريس',
    'complaints.staff': 'موظف',
    'complaints.other': 'أخرى',
    'complaints.program': 'البرنامج الأكاديمي',
    'complaints.selectProgram': 'اختر البرنامج (اختياري)',
    'complaints.semester': 'الفصل الدراسي',
    'complaints.selectSemester': 'اختر الفصل',
    'complaints.fall': 'خريف',
    'complaints.spring': 'ربيع',
    'complaints.summer': 'صيف',
    'complaints.academicYear': 'السنة الأكاديمية',
    'complaints.details': 'تفاصيل الشكوى',
    'complaints.category': 'نوع الشكوى',
    'complaints.academic': 'أكاديمية',
    'complaints.administrative': 'إدارية',
    'complaints.technical': 'تقنية',
    'complaints.complaintSubject': 'موضوع الشكوى',
    'complaints.complaintDetails': 'تفاصيل الشكوى',
    'complaints.attachments': 'المرفقات (اختياري)',
    'complaints.uploadFiles': 'انقر لرفع الملفات (PDF، صور، مستندات)',
    'complaints.filesSelected': 'تم اختيار ملف',
    'complaints.submitBtn': 'إرسال الشكوى',
    'complaints.cancel': 'إلغاء',
    'complaints.submitting': 'جاري الإرسال...',
    
    // Recommendations
    'recommendations.title': 'إدارة التوصيات',
    'recommendations.subtitle': 'متابعة وتنفيذ التوصيات التحسينية',
    'recommendations.add': 'إضافة توصية',
    'recommendations.edit': 'تعديل',
    'recommendations.priority': 'الأولوية',
    'recommendations.status': 'الحالة',
    'recommendations.high': 'عالية',
    'recommendations.medium': 'متوسطة',
    'recommendations.low': 'منخفضة',
    'recommendations.total': 'إجمالي التوصيات',
    'recommendations.completed': 'مكتملة',
    'recommendations.inProgress': 'قيد التنفيذ',
    'recommendations.pending': 'معلقة',
    'recommendations.completionRate': 'معدل الإنجاز',
    'recommendations.list': 'قائمة التوصيات',
    'recommendations.date': 'التاريخ',
    'recommendations.titleLabel': 'العنوان',
    'recommendations.programLabel': 'البرنامج',
    'recommendations.source': 'المصدر',
    'recommendations.actions': 'الإجراءات',
    'recommendations.addNew': 'إضافة توصية جديدة',
    'recommendations.editTitle': 'تعديل التوصية',
    'recommendations.addDescription': 'أضف توصية تحسينية جديدة',
    'recommendations.editDescription': 'قم بتعديل بيانات التوصية',
    'recommendations.recommendationTitle': 'عنوان التوصية',
    'recommendations.details': 'التفاصيل',
    'recommendations.selectProgram': 'اختر البرنامج',
    'recommendations.survey': 'استبيان',
    'recommendations.complaint': 'شكوى',
    'recommendations.manual': 'يدوي',
    'recommendations.selectSemester': 'اختر الفصل',
    'recommendations.first': 'الأول',
    'recommendations.second': 'الثاني',
    'recommendations.summerSem': 'الصيفي',
    'recommendations.saving': 'جاري الحفظ...',
    'recommendations.update': 'تحديث',
    
    // Reports
    'reports.title': 'التقارير والتحليلات',
    'reports.generate': 'إنشاء تقرير',
    'reports.download': 'تحميل',
    'reports.exportPdf': 'تصدير PDF',
    'reports.exportExcel': 'تصدير Excel',
    'reports.reanalyze': 'إعادة التحليل',
    'reports.analyzing': 'جاري التحليل...',
    'reports.deleteReport': 'حذف التقرير',
    'reports.noReport': 'لا يوجد تقرير',
    'reports.noReportDesc': 'لم يتم إنشاء تقرير لهذا الاستبيان بعد',
    'reports.createWithAI': 'إنشاء تقرير بالذكاء الاصطناعي',
    'reports.creating': 'جاري إنشاء التقرير...',
    'reports.backToSurveys': 'العودة إلى الاستبيانات',
    'reports.metadata': 'بيانات التقرير',
    'reports.metadataDesc': 'تحديد الفصل الدراسي وحالة التقرير',
    'reports.semester': 'الفصل الدراسي',
    'reports.academicYear': 'العام الأكاديمي',
    'reports.status': 'حالة التقرير',
    'reports.responding': 'تحت الاستجابة للردود',
    'reports.completed': 'منتهي',
    'reports.noResponse': 'لم يتم الاستجابة',
    'reports.cancelled': 'ملغي',
    'reports.saveMetadata': 'حفظ بيانات التقرير',
    'reports.totalResponses': 'إجمالي الاستجابات',
    'reports.response': 'استجابة',
    'reports.questionsCount': 'عدد الأسئلة',
    'reports.question': 'سؤال',
    'reports.overallMean': 'المتوسط العام',
    'reports.outOf5': 'من 5.0',
    'reports.stdDev': 'الانحراف المعياري',
    'reports.consistency': 'التجانس',
    'reports.aiSummary': 'ملخص تنفيذي من AI',
    'reports.aiSummaryDesc': 'تحليل آلي للنتائج والتوصيات',
    'reports.editContent': 'تعديل المحتوى',
    'reports.executiveSummary': 'الملخص التنفيذي:',
    'reports.recommendationsLabel': 'التوصيات:',
    'reports.questionDetails': 'تفاصيل النتائج حسب الأسئلة',
    'reports.questionDetailsDesc': 'إحصائيات تفصيلية لكل سؤال',
    'reports.answersCount': 'عدد الإجابات',
    'reports.mean': 'المتوسط',
    'reports.deviation': 'الانحراف',
    
    // Archives
    'archives.title': 'الأرشيف الفصلي',
    'archives.subtitle': 'إدارة وتنظيم الأرشيف الفصلي للاستبيانات والتقارير',
    'archives.view': 'عرض الأرشيف',
    'archives.restore': 'استعادة',
    'archives.archiveNew': 'أرشفة عنصر جديد',
    'archives.totalItems': 'إجمالي العناصر',
    'archives.surveys': 'الاستبيانات',
    'archives.reports': 'التقارير',
    'archives.complaints': 'الشكاوى',
    'archives.frozen': 'مجمدة',
    'archives.listView': 'عرض القائمة',
    'archives.timelineView': 'العرض الزمني',
    'archives.searchPlaceholder': 'البحث في الأرشيف...',
    'archives.allTypes': 'جميع الأنواع',
    'archives.allSemesters': 'جميع الفصول',
    'archives.allYears': 'جميع السنوات',
    'archives.recommendations': 'التوصيات',
    'archives.survey': 'استبيان',
    'archives.report': 'تقرير',
    'archives.complaint': 'شكوى',
    'archives.recommendation': 'توصية',
    'archives.archivedOn': 'أُرشف في',
    'archives.by': 'بواسطة',
    'archives.system': 'النظام',
    'archives.noItems': 'لا توجد عناصر مؤرشفة',
    'archives.noMatchingItems': 'لا توجد عناصر تطابق معايير البحث',
    'archives.noArchivedYet': 'لم يتم أرشفة أي عناصر بعد',
    'archives.academicYear': 'العام الأكاديمي',
    
    // Users
    'users.title': 'إدارة المستخدمين',
    'users.subtitle': 'إدارة المستخدمين والصلاحيات',
    'users.add': 'إضافة مستخدم',
    'users.role': 'الدور',
    'users.admin': 'مدير النظام',
    'users.coordinator': 'منسق البرنامج',
    'users.programManager': 'مدير البرنامج',
    'users.dean': 'العميد',
    'users.user': 'مستخدم',
    'users.usersList': 'قائمة المستخدمين',
    'users.name': 'الاسم',
    'users.email': 'البريد الإلكتروني',
    'users.program': 'البرنامج',
    'users.noProgram': 'لا يوجد',
    'users.notSet': 'غير محدد',
    'users.changeRole': 'تغيير الدور',
    'users.selectProgram': 'اختر البرنامج',
    'users.adminDesc': 'صلاحيات كاملة على كل شيء في النظام',
    'users.coordinatorDesc': 'إنشاء استبيانات + إدارة كاملة لبرنامجه',
    'users.programManagerDesc': 'الاطلاع على النتائج فقط لبرنامجه',
    'users.deanDesc': 'الاطلاع على نتائج جميع البرامج',
    
    // Settings
    'settings.title': 'إعدادات النظام',
    'settings.subtitle': 'إدارة إعدادات النظام العامة',
    'settings.general': 'عام',
    'settings.notifications': 'الإشعارات',
    'settings.security': 'الأمان',
    'settings.collegeLogo': 'شعار الكلية',
    'settings.logoUrl': 'رابط الشعار (URL)',
    'settings.save': 'حفظ',
    'settings.saving': 'جاري الحفظ...',
    'settings.logoDesc': 'أدخل رابط شعار الكلية. سيظهر في جميع التقارير المُصدرة.',
    'settings.logoPreview': 'معاينة الشعار',
    'settings.tips': 'نصائح:',
    'settings.tip1': 'استخدم صورة بخلفية شفافة (PNG) للحصول على أفضل نتيجة',
    'settings.tip2': 'الحجم الموصى به: 200x200 بكسل أو أكبر',
    'settings.tip3': 'تأكد من أن الرابط يعمل ويمكن الوصول إليه',
    
    // Comparison
    'comparison.title': 'مقارنة البرامج',
    'comparison.select': 'اختر البرامج للمقارنة',
    
    // Auth
    'auth.login': 'تسجيل الدخول',
    'auth.logout': 'تسجيل الخروج',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.register': 'إنشاء حساب',
    'auth.fullName': 'الاسم الكامل',
    'auth.program': 'البرنامج',
    'auth.selectProgram': 'اختر البرنامج',
    'auth.systemTitle': 'منظومة الاستبيانات الذكية',
    'auth.systemSubtitle': 'كلية العلوم الإنسانية والاجتماعية',
    'auth.loggingIn': 'جاري الدخول...',
    'auth.enter': 'دخول',
    'auth.creating': 'جاري الإنشاء...',
    'auth.createAccount': 'إنشاء حساب',
    
    // Common
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.add': 'إضافة',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    'common.loading': 'جاري التحميل...',
    'common.noData': 'لا توجد بيانات',
    'common.confirm': 'تأكيد',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.close': 'إغلاق',
    'common.actions': 'الإجراءات',
    'common.name': 'الاسم',
    'common.email': 'البريد الإلكتروني',
    'common.date': 'التاريخ',
    'common.program': 'البرنامج',
    'common.semester': 'الفصل الدراسي',
    'common.academicYear': 'السنة الأكاديمية',
    'common.back': 'رجوع',
    'common.copied': 'تم النسخ',
    'common.error': 'خطأ',
    'common.success': 'نجاح',
    'common.updated': 'تم التحديث',
    'common.deleted': 'تم الحذف',
    'common.saved': 'تم الحفظ',
    'common.unauthorized': 'غير مصرح',
    'common.adminOnly': 'هذه الصفحة متاحة للمديرين فقط',
    
    // Index/Landing
    'index.title': 'نظام إدارة الاستبيانات',
    'index.subtitle': 'منصة متكاملة لإدارة الاستبيانات والشكاوى',
    'index.getStarted': 'ابدأ الآن',
    'index.login': 'تسجيل الدخول',
    'index.features': 'المميزات',
    'index.feature1.title': 'استبيانات ذكية',
    'index.feature1.desc': 'إنشاء وإدارة استبيانات متنوعة بسهولة',
    'index.feature2.title': 'تحليلات متقدمة',
    'index.feature2.desc': 'تقارير وتحليلات تفصيلية للبيانات',
    'index.feature3.title': 'إدارة الشكاوى',
    'index.feature3.desc': 'نظام متكامل لإدارة ومتابعة الشكاوى',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.surveys': 'Surveys',
    'nav.complaints': 'Complaints',
    'nav.recommendations': 'Recommendations',
    'nav.archives': 'Archives',
    'nav.comparison': 'Program Comparison',
    'nav.users': 'Users',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.home': 'Home',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome to Survey Management System',
    'dashboard.welcomeUser': 'Welcome',
    'dashboard.systemTitle': 'Smart Survey System',
    'dashboard.totalSurveys': 'Total Surveys',
    'dashboard.activeSurveys': 'Active Surveys',
    'dashboard.totalResponses': 'Total Responses',
    'dashboard.responseRate': 'Response Rate',
    'dashboard.readyReports': 'Ready Reports',
    'dashboard.pendingComplaints': 'Pending Complaints',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.recentSurveys': 'Recent Surveys',
    'dashboard.recentSurveysDesc': 'Active surveys and response status',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.createSurvey': 'Create New Survey',
    'dashboard.newSurvey': 'New Survey',
    'dashboard.viewReports': 'View Reports',
    'dashboard.viewReport': 'View Report',
    'dashboard.manageComplaints': 'Manage Complaints',
    'dashboard.manageSurveys': 'Manage Surveys',
    'dashboard.noSurveys': 'No surveys currently',
    'dashboard.viewAllSurveys': 'View All Surveys',
    'dashboard.followRecommendations': 'Follow Recommendations',
    'dashboard.semesterArchive': 'Semester Archive',
    'dashboard.manageUsers': 'Manage Users',
    'dashboard.systemSettings': 'System Settings',
    'dashboard.response': 'response',
    
    // Surveys
    'surveys.title': 'Survey Management',
    'surveys.subtitle': 'View and manage surveys and templates',
    'surveys.create': 'Create Survey',
    'surveys.edit': 'Edit',
    'surveys.delete': 'Delete',
    'surveys.view': 'View',
    'surveys.status': 'Status',
    'surveys.responses': 'Responses',
    'surveys.actions': 'Actions',
    'surveys.draft': 'Draft',
    'surveys.active': 'Active',
    'surveys.closed': 'Closed',
    'surveys.noSurveys': 'No surveys found',
    'surveys.createFirst': 'Create First Survey',
    'surveys.newSurvey': 'New Survey',
    'surveys.templates': 'Templates',
    'surveys.updateQR': 'Update QR Codes',
    'surveys.searchPlaceholder': 'Search surveys...',
    'surveys.activate': 'Activate',
    'surveys.deactivate': 'Deactivate',
    'surveys.link': 'Link',
    'surveys.report': 'Report',
    'surveys.program': 'Program',
    'surveys.noTemplates': 'No saved templates',
    'surveys.createAndSaveTemplate': 'Create survey and save as template',
    'surveys.public': 'Public',
    'surveys.useTemplate': 'Use',
    
    // Complaints
    'complaints.title': 'Complaints Management',
    'complaints.subtitle': 'Track and process student and staff complaints',
    'complaints.submit': 'Submit Complaint',
    'complaints.submitNew': 'New Complaint',
    'complaints.status': 'Status',
    'complaints.pending': 'Under Review',
    'complaints.inProgress': 'In Progress',
    'complaints.resolved': 'Resolved',
    'complaints.closed': 'Closed',
    'complaints.subject': 'Subject',
    'complaints.description': 'Description',
    'complaints.type': 'Type',
    'complaints.date': 'Date',
    'complaints.total': 'Total Complaints',
    'complaints.submitComplaint': 'Submit Complaint',
    'complaints.submitTitle': 'Submit a Complaint',
    'complaints.submitSubtitle': 'We are here to listen to your feedback and complaints',
    'complaints.formTitle': 'Complaint Form',
    'complaints.formSubtitle': 'Please fill in all required fields (*)',
    'complaints.confidentialNote': 'All complaints are handled confidentially. Please provide accurate information to help us resolve the issue as quickly as possible.',
    'complaints.personalInfo': 'Personal Information',
    'complaints.fullName': 'Full Name',
    'complaints.email': 'Email',
    'complaints.academicId': 'Academic / Employee ID',
    'complaints.complainantType': 'Complainant Type',
    'complaints.student': 'Student',
    'complaints.faculty': 'Faculty Member',
    'complaints.staff': 'Staff',
    'complaints.other': 'Other',
    'complaints.program': 'Academic Program',
    'complaints.selectProgram': 'Select Program (optional)',
    'complaints.semester': 'Semester',
    'complaints.selectSemester': 'Select Semester',
    'complaints.fall': 'Fall',
    'complaints.spring': 'Spring',
    'complaints.summer': 'Summer',
    'complaints.academicYear': 'Academic Year',
    'complaints.details': 'Complaint Details',
    'complaints.category': 'Complaint Type',
    'complaints.academic': 'Academic',
    'complaints.administrative': 'Administrative',
    'complaints.technical': 'Technical',
    'complaints.complaintSubject': 'Complaint Subject',
    'complaints.complaintDetails': 'Complaint Details',
    'complaints.attachments': 'Attachments (optional)',
    'complaints.uploadFiles': 'Click to upload files (PDF, images, documents)',
    'complaints.filesSelected': 'file(s) selected',
    'complaints.submitBtn': 'Submit Complaint',
    'complaints.cancel': 'Cancel',
    'complaints.submitting': 'Submitting...',
    
    // Recommendations
    'recommendations.title': 'Recommendations Management',
    'recommendations.subtitle': 'Track and implement improvement recommendations',
    'recommendations.add': 'Add Recommendation',
    'recommendations.edit': 'Edit',
    'recommendations.priority': 'Priority',
    'recommendations.status': 'Status',
    'recommendations.high': 'High',
    'recommendations.medium': 'Medium',
    'recommendations.low': 'Low',
    'recommendations.total': 'Total Recommendations',
    'recommendations.completed': 'Completed',
    'recommendations.inProgress': 'In Progress',
    'recommendations.pending': 'Pending',
    'recommendations.completionRate': 'Completion Rate',
    'recommendations.list': 'Recommendations List',
    'recommendations.date': 'Date',
    'recommendations.titleLabel': 'Title',
    'recommendations.programLabel': 'Program',
    'recommendations.source': 'Source',
    'recommendations.actions': 'Actions',
    'recommendations.addNew': 'Add New Recommendation',
    'recommendations.editTitle': 'Edit Recommendation',
    'recommendations.addDescription': 'Add a new improvement recommendation',
    'recommendations.editDescription': 'Edit recommendation details',
    'recommendations.recommendationTitle': 'Recommendation Title',
    'recommendations.details': 'Details',
    'recommendations.selectProgram': 'Select Program',
    'recommendations.survey': 'Survey',
    'recommendations.complaint': 'Complaint',
    'recommendations.manual': 'Manual',
    'recommendations.selectSemester': 'Select Semester',
    'recommendations.first': 'First',
    'recommendations.second': 'Second',
    'recommendations.summerSem': 'Summer',
    'recommendations.saving': 'Saving...',
    'recommendations.update': 'Update',
    
    // Reports
    'reports.title': 'Reports & Analytics',
    'reports.generate': 'Generate Report',
    'reports.download': 'Download',
    'reports.exportPdf': 'Export PDF',
    'reports.exportExcel': 'Export Excel',
    'reports.reanalyze': 'Re-analyze',
    'reports.analyzing': 'Analyzing...',
    'reports.deleteReport': 'Delete Report',
    'reports.noReport': 'No Report',
    'reports.noReportDesc': 'No report has been created for this survey yet',
    'reports.createWithAI': 'Create Report with AI',
    'reports.creating': 'Creating report...',
    'reports.backToSurveys': 'Back to Surveys',
    'reports.metadata': 'Report Data',
    'reports.metadataDesc': 'Set semester and report status',
    'reports.semester': 'Semester',
    'reports.academicYear': 'Academic Year',
    'reports.status': 'Report Status',
    'reports.responding': 'Under Response',
    'reports.completed': 'Completed',
    'reports.noResponse': 'No Response',
    'reports.cancelled': 'Cancelled',
    'reports.saveMetadata': 'Save Report Data',
    'reports.totalResponses': 'Total Responses',
    'reports.response': 'response',
    'reports.questionsCount': 'Number of Questions',
    'reports.question': 'question',
    'reports.overallMean': 'Overall Mean',
    'reports.outOf5': 'out of 5.0',
    'reports.stdDev': 'Standard Deviation',
    'reports.consistency': 'Consistency',
    'reports.aiSummary': 'AI Executive Summary',
    'reports.aiSummaryDesc': 'Automated analysis of results and recommendations',
    'reports.editContent': 'Edit Content',
    'reports.executiveSummary': 'Executive Summary:',
    'reports.recommendationsLabel': 'Recommendations:',
    'reports.questionDetails': 'Results by Question',
    'reports.questionDetailsDesc': 'Detailed statistics for each question',
    'reports.answersCount': 'Answer Count',
    'reports.mean': 'Mean',
    'reports.deviation': 'Deviation',
    
    // Archives
    'archives.title': 'Semester Archive',
    'archives.subtitle': 'Manage and organize semester archives for surveys and reports',
    'archives.view': 'View Archive',
    'archives.restore': 'Restore',
    'archives.archiveNew': 'Archive New Item',
    'archives.totalItems': 'Total Items',
    'archives.surveys': 'Surveys',
    'archives.reports': 'Reports',
    'archives.complaints': 'Complaints',
    'archives.frozen': 'Frozen',
    'archives.listView': 'List View',
    'archives.timelineView': 'Timeline View',
    'archives.searchPlaceholder': 'Search archive...',
    'archives.allTypes': 'All Types',
    'archives.allSemesters': 'All Semesters',
    'archives.allYears': 'All Years',
    'archives.recommendations': 'Recommendations',
    'archives.survey': 'Survey',
    'archives.report': 'Report',
    'archives.complaint': 'Complaint',
    'archives.recommendation': 'Recommendation',
    'archives.archivedOn': 'Archived on',
    'archives.by': 'by',
    'archives.system': 'System',
    'archives.noItems': 'No archived items',
    'archives.noMatchingItems': 'No items match the search criteria',
    'archives.noArchivedYet': 'No items have been archived yet',
    'archives.academicYear': 'Academic Year',
    
    // Users
    'users.title': 'User Management',
    'users.subtitle': 'Manage users and permissions',
    'users.add': 'Add User',
    'users.role': 'Role',
    'users.admin': 'System Admin',
    'users.coordinator': 'Program Coordinator',
    'users.programManager': 'Program Manager',
    'users.dean': 'Dean',
    'users.user': 'User',
    'users.usersList': 'Users List',
    'users.name': 'Name',
    'users.email': 'Email',
    'users.program': 'Program',
    'users.noProgram': 'None',
    'users.notSet': 'Not set',
    'users.changeRole': 'Change Role',
    'users.selectProgram': 'Select Program',
    'users.adminDesc': 'Full permissions on everything in the system',
    'users.coordinatorDesc': 'Create surveys + full management of their program',
    'users.programManagerDesc': 'View results only for their program',
    'users.deanDesc': 'View results of all programs',
    
    // Settings
    'settings.title': 'System Settings',
    'settings.subtitle': 'Manage general system settings',
    'settings.general': 'General',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security',
    'settings.collegeLogo': 'College Logo',
    'settings.logoUrl': 'Logo URL',
    'settings.save': 'Save',
    'settings.saving': 'Saving...',
    'settings.logoDesc': 'Enter the college logo URL. It will appear in all exported reports.',
    'settings.logoPreview': 'Logo Preview',
    'settings.tips': 'Tips:',
    'settings.tip1': 'Use an image with a transparent background (PNG) for the best result',
    'settings.tip2': 'Recommended size: 200x200 pixels or larger',
    'settings.tip3': 'Make sure the link works and is accessible',
    
    // Comparison
    'comparison.title': 'Program Comparison',
    'comparison.select': 'Select programs to compare',
    
    // Auth
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.register': 'Register',
    'auth.fullName': 'Full Name',
    'auth.program': 'Program',
    'auth.selectProgram': 'Select Program',
    'auth.systemTitle': 'Smart Survey System',
    'auth.systemSubtitle': 'College of Humanities and Social Sciences',
    'auth.loggingIn': 'Logging in...',
    'auth.enter': 'Login',
    'auth.creating': 'Creating...',
    'auth.createAccount': 'Create Account',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.loading': 'Loading...',
    'common.noData': 'No data available',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.close': 'Close',
    'common.actions': 'Actions',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.date': 'Date',
    'common.program': 'Program',
    'common.semester': 'Semester',
    'common.academicYear': 'Academic Year',
    'common.back': 'Back',
    'common.copied': 'Copied',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.updated': 'Updated',
    'common.deleted': 'Deleted',
    'common.saved': 'Saved',
    'common.unauthorized': 'Unauthorized',
    'common.adminOnly': 'This page is available to admins only',
    
    // Index/Landing
    'index.title': 'Survey Management System',
    'index.subtitle': 'Integrated platform for managing surveys and complaints',
    'index.getStarted': 'Get Started',
    'index.login': 'Login',
    'index.features': 'Features',
    'index.feature1.title': 'Smart Surveys',
    'index.feature1.desc': 'Create and manage various surveys easily',
    'index.feature2.title': 'Advanced Analytics',
    'index.feature2.desc': 'Detailed reports and data analytics',
    'index.feature3.title': 'Complaint Management',
    'index.feature3.desc': 'Integrated system for managing and tracking complaints',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'ar';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
