import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'rtl' | 'ltr';
}

const translations: Record<Language, Record<string, string>> = {
  ar: {
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.surveys': 'الاستبيانات',
    'nav.complaints': 'الشكاوى',
    'nav.recommendations': 'التوصيات',
    'nav.archives': 'الأرشيف',
    'nav.comparison': 'مقارنة البرامج',
    'nav.users': 'المستخدمون',
    'nav.settings': 'الإعدادات',
    'nav.logout': 'تسجيل الخروج',
    'nav.home': 'الصفحة الرئيسية',
    
    // Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.welcome': 'مرحباً بك في نظام إدارة الاستبيانات',
    'dashboard.welcomeUser': 'مرحباً',
    'dashboard.systemTitle': 'منظومة الاستبيانات الذكية',
    'dashboard.totalSurveys': 'إجمالي الاستبيانات',
    'dashboard.activeSurveys': 'الاستبيانات النشطة',
    'dashboard.totalResponses': 'إجمالي الاستجابات',
    'dashboard.responseRate': 'معدل الاستجابة',
    'dashboard.readyReports': 'التقارير الجاهزة',
    'dashboard.pendingComplaints': 'الشكاوى المعلقة',
    'dashboard.recentActivity': 'النشاط الأخير',
    'dashboard.recentSurveys': 'الاستبيانات الأخيرة',
    'dashboard.recentSurveysDesc': 'الاستبيانات النشطة وحالة الاستجابات',
    'dashboard.quickActions': 'الإجراءات السريعة',
    'dashboard.createSurvey': 'إنشاء استبيان جديد',
    'dashboard.newSurvey': 'استبيان جديد',
    'dashboard.viewReports': 'عرض التقارير',
    'dashboard.viewReport': 'عرض التقرير',
    'dashboard.manageComplaints': 'إدارة الشكاوى',
    'dashboard.manageSurveys': 'إدارة الاستبيانات',
    'dashboard.noSurveys': 'لا توجد استبيانات حالياً',
    'dashboard.viewAllSurveys': 'عرض جميع الاستبيانات',
    'dashboard.followRecommendations': 'متابعة التوصيات',
    'dashboard.semesterArchive': 'الأرشيف الفصلي',
    'dashboard.manageUsers': 'إدارة المستخدمين',
    'dashboard.systemSettings': 'إعدادات النظام',
    'dashboard.response': 'استجابة',
    
    // Surveys
    'surveys.title': 'إدارة الاستبيانات',
    'surveys.subtitle': 'عرض وإدارة الاستبيانات والنماذج',
    'surveys.create': 'إنشاء استبيان',
    'surveys.edit': 'تعديل',
    'surveys.delete': 'حذف',
    'surveys.view': 'عرض',
    'surveys.status': 'الحالة',
    'surveys.responses': 'الردود',
    'surveys.actions': 'الإجراءات',
    'surveys.draft': 'مسودة',
    'surveys.active': 'نشط',
    'surveys.closed': 'مغلق',
    'surveys.noSurveys': 'لا توجد استبيانات',
    'surveys.createFirst': 'إنشاء أول استبيان',
    'surveys.newSurvey': 'استبيان جديد',
    'surveys.templates': 'النماذج',
    'surveys.updateQR': 'تحديث رموز QR',
    'surveys.searchPlaceholder': 'البحث في الاستبيانات...',
    'surveys.activate': 'تفعيل',
    'surveys.deactivate': 'إيقاف',
    'surveys.link': 'رابط',
    'surveys.report': 'التقرير',
    'surveys.program': 'برنامج',
    'surveys.noTemplates': 'لا توجد نماذج محفوظة',
    'surveys.createAndSaveTemplate': 'إنشاء استبيان وحفظه كنموذج',
    'surveys.public': 'عام',
    'surveys.useTemplate': 'استخدام',
    
    // Complaints
    'complaints.title': 'إدارة الشكاوى',
    'complaints.subtitle': 'متابعة ومعالجة شكاوى الطلاب والموظفين',
    'complaints.submit': 'تقديم شكوى',
    'complaints.submitNew': 'شكوى جديدة',
    'complaints.status': 'الحالة',
    'complaints.pending': 'قيد المراجعة',
    'complaints.inProgress': 'قيد المعالجة',
    'complaints.resolved': 'تم الحل',
    'complaints.closed': 'مغلقة',
    'complaints.subject': 'الموضوع',
    'complaints.description': 'الوصف',
    'complaints.type': 'النوع',
    'complaints.date': 'التاريخ',
    'complaints.total': 'إجمالي الشكاوى',
    'complaints.submitComplaint': 'تقديم شكوى',
    'complaints.submitTitle': 'تقديم شكوى',
    'complaints.submitSubtitle': 'نحن هنا للاستماع إلى ملاحظاتك وشكاواك',
    'complaints.formTitle': 'نموذج الشكوى',
    'complaints.formSubtitle': 'يرجى ملء جميع الحقول المطلوبة (*)',
    'complaints.confidentialNote': 'جميع الشكاوى يتم معالجتها بسرية تامة. يرجى تقديم معلومات دقيقة لمساعدتنا في حل المشكلة بأسرع وقت ممكن.',
    'complaints.personalInfo': 'المعلومات الشخصية',
    'complaints.fullName': 'الاسم الكامل',
    'complaints.email': 'البريد الإلكتروني',
    'complaints.academicId': 'الرقم الأكاديمي / الوظيفي',
    'complaints.complainantType': 'نوع المشتكي',
    'complaints.student': 'طالب',
    'complaints.faculty': 'عضو هيئة تدريس',
    'complaints.staff': 'موظف',
    'complaints.other': 'أخرى',
    'complaints.program': 'البرنامج الأكاديمي',
    'complaints.selectProgram': 'اختر البرنامج (اختياري)',
    'complaints.semester': 'الفصل الدراسي',
    'complaints.selectSemester': 'اختر الفصل',
    'complaints.fall': 'خريف',
    'complaints.spring': 'ربيع',
    'complaints.summer': 'صيف',
    'complaints.academicYear': 'السنة الأكاديمية',
    'complaints.details': 'تفاصيل الشكوى',
    'complaints.category': 'نوع الشكوى',
    'complaints.academic': 'أكاديمية',
    'complaints.administrative': 'إدارية',
    'complaints.technical': 'تقنية',
    'complaints.complaintSubject': 'موضوع الشكوى',
    'complaints.complaintDetails': 'تفاصيل الشكوى',
    'complaints.attachments': 'المرفقات (اختياري)',
    'complaints.uploadFiles': 'انقر لرفع الملفات (PDF، صور، مستندات)',
    'complaints.filesSelected': 'تم اختيار ملف',
    'complaints.submitBtn': 'إرسال الشكوى',
    'complaints.cancel': 'إلغاء',
    'complaints.submitting': 'جاري الإرسال...',
    
    // Recommendations
    'recommendations.title': 'إدارة التوصيات',
    'recommendations.subtitle': 'متابعة وتنفيذ التوصيات التحسينية',
    'recommendations.add': 'إضافة توصية',
    'recommendations.edit': 'تعديل',
    'recommendations.priority': 'الأولوية',
    'recommendations.status': 'الحالة',
    'recommendations.high': 'عالية',
    'recommendations.medium': 'متوسطة',
    'recommendations.low': 'منخفضة',
    'recommendations.total': 'إجمالي التوصيات',
    'recommendations.completed': 'مكتملة',
    'recommendations.inProgress': 'قيد التنفيذ',
    'recommendations.pending': 'معلقة',
    'recommendations.completionRate': 'معدل الإنجاز',
    'recommendations.list': 'قائمة التوصيات',
    'recommendations.date': 'التاريخ',
    'recommendations.titleLabel': 'العنوان',
    'recommendations.programLabel': 'البرنامج',
    'recommendations.source': 'المصدر',
    'recommendations.actions': 'الإجراءات',
    'recommendations.addNew': 'إضافة توصية جديدة',
    'recommendations.editTitle': 'تعديل التوصية',
    'recommendations.addDescription': 'أضف توصية تحسينية جديدة',
    'recommendations.editDescription': 'قم بتعديل بيانات التوصية',
    'recommendations.recommendationTitle': 'عنوان التوصية',
    'recommendations.details': 'التفاصيل',
    'recommendations.selectProgram': 'اختر البرنامج',
    'recommendations.survey': 'استبيان',
    'recommendations.complaint': 'شكوى',
    'recommendations.manual': 'يدوي',
    'recommendations.selectSemester': 'اختر الفصل',
    'recommendations.first': 'الأول',
    'recommendations.second': 'الثاني',
    'recommendations.summerSem': 'الصيفي',
    'recommendations.saving': 'جاري الحفظ...',
    'recommendations.update': 'تحديث',
    
    // Reports
    'reports.title': 'التقارير والتحليلات',
    'reports.generate': 'إنشاء تقرير',
    'reports.download': 'تحميل',
    'reports.exportPdf': 'تصدير PDF',
    'reports.exportExcel': 'تصدير Excel',
    'reports.reanalyze': 'إعادة التحليل',
    'reports.analyzing': 'جاري التحليل...',
    'reports.deleteReport': 'حذف التقرير',
    'reports.noReport': 'لا يوجد تقرير',
    'reports.noReportDesc': 'لم يتم إنشاء تقرير لهذا الاستبيان بعد',
    'reports.createWithAI': 'إنشاء تقرير بالذكاء الاصطناعي',
    'reports.creating': 'جاري إنشاء التقرير...',
    'reports.backToSurveys': 'العودة إلى الاستبيانات',
    'reports.metadata': 'بيانات التقرير',
    'reports.metadataDesc': 'تحديد الفصل الدراسي وحالة التقرير',
    'reports.semester': 'الفصل الدراسي',
    'reports.academicYear': 'العام الأكاديمي',
    'reports.status': 'حالة التقرير',
    'reports.responding': 'تحت الاستجابة للردود',
    'reports.completed': 'منتهي',
    'reports.noResponse': 'لم يتم الاستجابة',
    'reports.cancelled': 'ملغي',
    'reports.saveMetadata': 'حفظ بيانات التقرير',
    'reports.totalResponses': 'إجمالي الاستجابات',
    'reports.response': 'استجابة',
    'reports.questionsCount': 'عدد الأسئلة',
    'reports.question': 'سؤال',
    'reports.overallMean': 'المتوسط العام',
    'reports.outOf5': 'من 5.0',
    'reports.stdDev': 'الانحراف المعياري',
    'reports.consistency': 'التجانس',
    'reports.aiSummary': 'ملخص تنفيذي من AI',
    'reports.aiSummaryDesc': 'تحليل آلي للنتائج والتوصيات',
    'reports.editContent': 'تعديل المحتوى',
    'reports.executiveSummary': 'الملخص التنفيذي:',
    'reports.recommendationsLabel': 'التوصيات:',
    'reports.questionDetails': 'تفاصيل النتائج حسب الأسئلة',
    'reports.questionDetailsDesc': 'إحصائيات تفصيلية لكل سؤال',
    'reports.answersCount': 'عدد الإجابات',
    'reports.mean': 'المتوسط',
    'reports.deviation': 'الانحراف',
    
    // Archives
    'archives.title': 'الأرشيف الفصلي',
    'archives.subtitle': 'إدارة وتنظيم الأرشيف الفصلي للاستبيانات والتقارير',
    'archives.view': 'عرض الأرشيف',
    'archives.restore': 'استعادة',
    'archives.archiveNew': 'أرشفة عنصر جديد',
    'archives.totalItems': 'إجمالي العناصر',
    'archives.surveys': 'الاستبيانات',
    'archives.reports': 'التقارير',
    'archives.complaints': 'الشكاوى',
    'archives.frozen': 'مجمدة',
    'archives.listView': 'عرض القائمة',
    'archives.timelineView': 'العرض الزمني',
    'archives.searchPlaceholder': 'البحث في الأرشيف...',
    'archives.allTypes': 'جميع الأنواع',
    'archives.allSemesters': 'جميع الفصول',
    'archives.allYears': 'جميع السنوات',
    'archives.recommendations': 'التوصيات',
    'archives.survey': 'استبيان',
    'archives.report': 'تقرير',
    'archives.complaint': 'شكوى',
    'archives.recommendation': 'توصية',
    'archives.archivedOn': 'أُرشف في',
    'archives.by': 'بواسطة',
    'archives.system': 'النظام',
    'archives.noItems': 'لا توجد عناصر مؤرشفة',
    'archives.noMatchingItems': 'لا توجد عناصر تطابق معايير البحث',
    'archives.noArchivedYet': 'لم يتم أرشفة أي عناصر بعد',
    'archives.academicYear': 'العام الأكاديمي',
    
    // Users
    'users.title': 'إدارة المستخدمين',
    'users.subtitle': 'إدارة المستخدمين والصلاحيات',
    'users.add': 'إضافة مستخدم',
    'users.role': 'الدور',
    'users.admin': 'مدير النظام',
    'users.coordinator': 'منسق البرنامج',
    'users.programManager': 'مدير البرنامج',
    'users.dean': 'العميد',
    'users.user': 'مستخدم',
    'users.usersList': 'قائمة المستخدمين',
    'users.name': 'الاسم',
    'users.email': 'البريد الإلكتروني',
    'users.program': 'البرنامج',
    'users.noProgram': 'لا يوجد',
    'users.notSet': 'غير محدد',
    'users.changeRole': 'تغيير الدور',
    'users.selectProgram': 'اختر البرنامج',
    'users.adminDesc': 'صلاحيات كاملة على كل شيء في النظام',
    'users.coordinatorDesc': 'إنشاء استبيانات + إدارة كاملة لبرنامجه',
    'users.programManagerDesc': 'الاطلاع على النتائج فقط لبرنامجه',
    'users.deanDesc': 'الاطلاع على نتائج جميع البرامج',
    
    // Settings
    'settings.title': 'إعدادات النظام',
    'settings.subtitle': 'إدارة إعدادات النظام العامة',
    'settings.general': 'عام',
    'settings.notifications': 'الإشعارات',
    'settings.security': 'الأمان',
    'settings.collegeLogo': 'شعار الكلية',
    'settings.logoUrl': 'رابط الشعار (URL)',
    'settings.save': 'حفظ',
    'settings.saving': 'جاري الحفظ...',
    'settings.logoDesc': 'أدخل رابط شعار الكلية. سيظهر في جميع التقارير المُصدرة.',
    'settings.logoPreview': 'معاينة الشعار',
    'settings.tips': 'نصائح:',
    'settings.tip1': 'استخدم صورة بخلفية شفافة (PNG) للحصول على أفضل نتيجة',
    'settings.tip2': 'الحجم الموصى به: 200x200 بكسل أو أكبر',
    'settings.tip3': 'تأكد من أن الرابط يعمل ويمكن الوصول إليه',
    
    // Comparison
    'comparison.title': 'مقارنة البرامج',
    'comparison.subtitle': 'قارن أداء البرامج الأكاديمية المختلفة',
    'comparison.select': 'اختر البرامج للمقارنة',
    'comparison.academicYear': 'العام الأكاديمي',
    'comparison.semester': 'الفصل الدراسي',
    'comparison.allSemesters': 'جميع الفصول',
    'comparison.selectPrograms': 'اختر البرامج (2+)',
    'comparison.addProgram': 'أضف برنامج',
    'comparison.compare': 'مقارنة',
    'comparison.overallPerformance': 'الأداء العام',
    'comparison.noData': 'لا توجد بيانات للمقارنة',
    'comparison.selectAtLeast2': 'يرجى اختيار برنامجين على الأقل',
    'comparison.selectYear': 'يرجى اختيار العام الأكاديمي',
    'comparison.bestProgram': 'أفضل برنامج',
    'comparison.satisfactionRate': 'نسبة الرضا',
    'comparison.notAvailable': 'غير متوفر',

    // Survey Designer
    'designer.title': 'تصميم الاستبيان',
    'designer.editTitle': 'تعديل الاستبيان',
    'designer.surveyTitle': 'عنوان الاستبيان',
    'designer.surveyDescription': 'وصف الاستبيان',
    'designer.program': 'البرنامج',
    'designer.selectProgram': 'اختر البرنامج',
    'designer.anonymous': 'استبيان مجهول',
    'designer.startDate': 'تاريخ البداية',
    'designer.endDate': 'تاريخ النهاية',
    'designer.semester': 'الفصل الدراسي',
    'designer.academicYear': 'السنة الأكاديمية',
    'designer.targetEnrollment': 'عدد الطلبة المستهدف',
    'designer.addQuestion': 'إضافة سؤال',
    'designer.addSection': 'إضافة قسم',
    'designer.save': 'حفظ الاستبيان',
    'designer.saving': 'جاري الحفظ...',
    'designer.saveTemplate': 'حفظ كنموذج',
    'designer.preview': 'معاينة',
    'designer.design': 'التصميم',
    'designer.templates': 'القوالب',
    'designer.questionText': 'نص السؤال',
    'designer.sectionTitle': 'عنوان القسم',
    'designer.questionType': 'نوع السؤال',
    'designer.required': 'مطلوب',
    'designer.options': 'الخيارات',
    'designer.addOption': 'إضافة خيار',
    'designer.duplicate': 'نسخ',
    'designer.importExport': 'استيراد/تصدير',
    'designer.importJSON': 'استيراد JSON',
    'designer.importCSV': 'استيراد CSV',
    'designer.exportJSON': 'تصدير JSON',
    'designer.exportCSV': 'تصدير CSV',
    'designer.likert': 'مقياس ليكرت',
    'designer.likertDesc': 'مقياس من 1-5 للموافقة',
    'designer.text': 'نص مفتوح',
    'designer.textDesc': 'إجابة نصية حرة',
    'designer.mcq': 'اختيارات متعددة',
    'designer.mcqDesc': 'اختيار من عدة خيارات',
    'designer.rating': 'تقييم/ترتيب',
    'designer.ratingDesc': 'تقييم بالنجوم أو ترتيب',
    'designer.section': 'عنوان قسم',
    'designer.sectionDesc': 'عنوان لتجميع الأسئلة',
    'designer.suggestWithAI': 'اقتراح بالذكاء الاصطناعي',
    'designer.existingResponses': 'يوجد استجابات سابقة',
    'designer.existingResponsesWarning': 'هذا الاستبيان يحتوي على استجابات. تعديل الأسئلة قد يؤثر على البيانات.',
    'designer.enterTitleAndProgram': 'الرجاء إدخال عنوان الاستبيان واختيار البرنامج',
    'designer.enterAllQuestions': 'الرجاء إدخال نص جميع الأسئلة',
    'designer.surveyUpdated': 'تم تحديث الاستبيان بنجاح',
    'designer.surveySaved': 'تم حفظ الاستبيان بنجاح',
    'designer.createCustom': 'إنشاء استبيان مخصص',
    'designer.createCustomDesc': 'ابدأ من الصفر وأنشئ استبياناً حسب احتياجاتك',
    'designer.useTemplate': 'استخدام القالب',
    'designer.questions': 'سؤال',

    // Take Survey
    'takeSurvey.loading': 'جاري تحميل الاستبيان...',
    'takeSurvey.notFound': 'الاستبيان غير موجود',
    'takeSurvey.notFoundDesc': 'لم يتم العثور على الاستبيان المطلوب',
    'takeSurvey.inactive': 'الاستبيان غير متاح',
    'takeSurvey.inactiveDesc': 'هذا الاستبيان غير نشط حالياً. يرجى التواصل مع منسق البرنامج.',
    'takeSurvey.stronglyDisagree': 'غير موافق بشدة',
    'takeSurvey.disagree': 'غير موافق',
    'takeSurvey.neutral': 'محايد',
    'takeSurvey.agree': 'موافق',
    'takeSurvey.stronglyAgree': 'موافق بشدة',
    'takeSurvey.next': 'التالي',
    'takeSurvey.previous': 'السابق',
    'takeSurvey.submit': 'إرسال',
    'takeSurvey.submitting': 'جاري الإرسال...',
    'takeSurvey.questionRequired': 'هذا السؤال مطلوب',
    'takeSurvey.requiredQuestions': 'أسئلة مطلوبة',
    'takeSurvey.remainingQuestions': 'سؤال متبقي',
    'takeSurvey.submitted': 'تم إرسال الاستبيان',
    'takeSurvey.thankYou': 'شكراً لك على مشاركتك في الاستبيان',
    'takeSurvey.selectRating': 'اختر التقييم',
    'takeSurvey.starsOf5': 'من 5 نجوم',
    'takeSurvey.answerPlaceholder': 'أدخل إجابتك هنا...',
    'takeSurvey.questionOf': 'سؤال',
    'takeSurvey.of': 'من',
    'takeSurvey.anonymous': 'استبيان مجهول',
    'takeSurvey.named': 'استبيان بالاسم',

    // Survey Complete
    'surveyComplete.title': 'شكراً لمشاركتك!',
    'surveyComplete.description': 'تم إرسال إجاباتك بنجاح. نقدر وقتك ومساهمتك في تحسين جودة التعليم.',
    'surveyComplete.retake': 'تعبئة الاستبيان مرة أخرى',

    // Complaint Submitted
    'complaintSubmitted.title': 'تم إرسال الشكوى بنجاح',
    'complaintSubmitted.description': 'شكراً لك. تم استلام شكواك وسيتم مراجعتها قريباً.',
    'complaintSubmitted.trackingNote': 'يمكنك متابعة حالة شكواك عبر النظام.',
    'complaintSubmitted.backHome': 'العودة للصفحة الرئيسية',
    'complaintSubmitted.submitAnother': 'تقديم شكوى أخرى',

    // Academic Calendar
    'calendar.title': 'الأجندة الأكاديمية',
    'calendar.subtitle': 'إدارة الفصول الدراسية والسنوات الأكاديمية',
    'calendar.addSemester': 'إضافة فصل دراسي',
    'calendar.addNew': 'إضافة فصل دراسي جديد',
    'calendar.editSemester': 'تعديل الفصل الدراسي',
    'calendar.semesters': 'الفصول الدراسية',
    'calendar.semestersDesc': 'قائمة بجميع الفصول الدراسية والسنوات الأكاديمية المسجلة',
    'calendar.academicYear': 'السنة الأكاديمية',
    'calendar.selectYear': 'اختر السنة الأكاديمية',
    'calendar.semester': 'الفصل الدراسي',
    'calendar.selectSemester': 'اختر الفصل الدراسي',
    'calendar.startDate': 'تاريخ البداية',
    'calendar.endDate': 'تاريخ النهاية',
    'calendar.status': 'الحالة',
    'calendar.actions': 'الإجراءات',
    'calendar.current': 'الفصل الحالي',
    'calendar.inactive': 'غير نشط',
    'calendar.setCurrent': 'تعيين كفصل حالي',
    'calendar.noSemesters': 'لا توجد فصول دراسية مسجلة',
    'calendar.addToStart': 'قم بإضافة فصل دراسي جديد للبدء',
    'calendar.first': 'الفصل الأول',
    'calendar.second': 'الفصل الثاني',
    'calendar.summer': 'الفصل الصيفي',
    'calendar.fillAllFields': 'الرجاء تعبئة جميع الحقول',
    'calendar.duplicateError': 'هذا الفصل الدراسي موجود مسبقًا لهذه السنة الأكاديمية',
    'calendar.added': 'تمت الإضافة',
    'calendar.addSuccess': 'تم إضافة الفصل الدراسي بنجاح',
    'calendar.updateSuccess': 'تم تحديث الفصل الدراسي بنجاح',
    'calendar.deleteSuccess': 'تم حذف الفصل الدراسي بنجاح',
    'calendar.setCurrentSuccess': 'تم تعيين الفصل الدراسي الحالي بنجاح',
    'calendar.confirmDelete': 'تأكيد حذف الفصل الدراسي',
    'calendar.confirmDeleteDesc': 'هل أنت متأكد من حذف هذا الفصل الدراسي؟ لا يمكن التراجع عن هذا الإجراء.',

    // Not Found
    'notFound.title': '404',
    'notFound.message': 'الصفحة غير موجودة',
    'notFound.back': 'العودة للصفحة الرئيسية',

    // QR Code Dialog
    'qr.title': 'رمز الاستجابة السريع',
    'qr.description': 'يمكن مسح هذا الرمز للوصول المباشر إلى الاستبيان',
    'qr.download': 'تنزيل الرمز',
    'qr.copyLink': 'نسخ الرابط',
    'qr.downloaded': 'تم التنزيل',
    'qr.downloadSuccess': 'تم تنزيل رمز الاستجابة السريع بنجاح',

    // Add User Dialog
    'addUser.title': 'إضافة مستخدم جديد',
    'addUser.description': 'أضف مستخدماً جديداً للنظام. سيُطلب منه تغيير كلمة المرور عند أول تسجيل دخول.',
    'addUser.fullName': 'الاسم الكامل',
    'addUser.email': 'البريد الإلكتروني',
    'addUser.password': 'كلمة المرور المؤقتة',
    'addUser.defaultPassword': 'كلمة المرور الافتراضية: 123456789',
    'addUser.adding': 'جارٍ الإضافة...',
    'addUser.add': 'إضافة المستخدم',
    'addUser.success': 'تم إضافة المستخدم',
    'addUser.fillRequired': 'يرجى ملء جميع الحقول المطلوبة',

    // User Roles Dialog
    'roles.title': 'إدارة صلاحيات',
    'roles.description': 'يمكنك إضافة صلاحيات متعددة للمستخدم على برامج مختلفة',
    'roles.noRoles': 'لا توجد صلاحيات محددة لهذا المستخدم',
    'roles.addNew': 'إضافة صلاحية جديدة',
    'roles.selectRole': 'اختر الدور',
    'roles.allPrograms': 'صلاحية كاملة على جميع البرامج',
    'roles.viewAll': 'الاطلاع على جميع البرامج',
    'roles.summary': 'ملخص الصلاحيات:',
    'roles.saveRoles': 'حفظ الصلاحيات',
    'roles.saved': 'تم تحديث صلاحيات المستخدم بنجاح',
    'roles.managePermissions': 'إدارة الصلاحيات',
    'roles.noPermissions': 'لا توجد صلاحيات',
    'roles.faculty': 'عضو هيئة تدريس',

    // Reset Password Dialog
    'resetPassword.title': 'إعادة تعيين كلمة المرور',
    'resetPassword.confirm': 'هل أنت متأكد من إعادة تعيين كلمة المرور للمستخدم',
    'resetPassword.newPassword': 'كلمة المرور الجديدة:',
    'resetPassword.note': 'سيُطلب من المستخدم تغيير كلمة المرور عند تسجيل الدخول التالي.',
    'resetPassword.resetting': 'جارٍ إعادة التعيين...',
    'resetPassword.reset': 'إعادة تعيين كلمة المرور',
    'resetPassword.success': 'تم إعادة تعيين كلمة المرور',

    // Delete User Dialog
    'deleteUser.title': 'تأكيد حذف المستخدم',
    'deleteUser.confirm': 'هل أنت متأكد من حذف المستخدم',
    'deleteUser.warning': 'هذا الإجراء لا يمكن التراجع عنه وسيتم حذف جميع بيانات المستخدم.',
    'deleteUser.deleting': 'جارٍ الحذف...',
    'deleteUser.delete': 'حذف المستخدم',

    // PDF Preview
    'pdfPreview.title': 'معاينة التقرير',
    'pdfPreview.generating': 'جاري إنشاء التقرير...',
    'pdfPreview.pleaseWait': 'يرجى الانتظار',
    'pdfPreview.noFile': 'لا يوجد ملف للمعاينة',
    'pdfPreview.download': 'تحميل PDF',

    // Survey Analytics
    'analytics.title': 'تحليل الاستبيان',
    'analytics.subtitle': 'نظرة شاملة على نتائج الاستبيان',
    'analytics.totalResponses': 'إجمالي الاستجابات',
    'analytics.completionRate': 'معدل الإكمال',
    'analytics.avgTime': 'متوسط الوقت',
    'analytics.noData': 'لا توجد بيانات',
    'analytics.noDataDesc': 'لا توجد استجابات كافية لعرض التحليل',
    'analytics.filter': 'تصفية',
    'analytics.all': 'الكل',
    'analytics.last7days': 'آخر 7 أيام',
    'analytics.last30days': 'آخر 30 يوم',
    'analytics.last90days': 'آخر 90 يوم',
    'analytics.timePeriod': 'الفترة الزمنية',
    'analytics.exportReport': 'تصدير التقرير',
    'analytics.exporting': 'جاري التصدير...',
    'analytics.exportFormat': 'صيغة التصدير',
    'analytics.exportSuccess': 'تم التصدير',
    'analytics.exportedPDF': 'تم تصدير التقرير بنجاح كملف PDF',
    'analytics.exportedExcel': 'تم تصدير التقرير بنجاح كملف Excel',

    // Complaints Dashboard
    'complaintsDash.title': 'لوحة تحكم الشكاوى',
    'complaintsDash.allPrograms': 'نظرة شاملة على جميع شكاوى الكلية',
    'complaintsDash.myProgram': 'شكاوى برنامجك الأكاديمي',
    'complaintsDash.filterByProgram': 'فلترة حسب البرنامج:',
    'complaintsDash.totalComplaints': 'إجمالي الشكاوى',
    'complaintsDash.newComplaints': 'شكاوى جديدة',
    'complaintsDash.inAction': 'قيد الإجراء',
    'complaintsDash.resolved': 'تم الحل',
    'complaintsDash.resolutionRate': 'نسبة الحل',
    'complaintsDash.resolvedOf': 'تم حل {0} من أصل {1} شكوى',
    'complaintsDash.byStatus': 'توزيع الشكاوى حسب الحالة',
    'complaintsDash.byComplainant': 'توزيع الشكاوى حسب مقدم الشكوى',
    'complaintsDash.programComparison': 'مقارنة أداء البرامج في معالجة الشكاوى',
    'complaintsDash.programComparisonDesc': 'عدد الشكاوى ونسبة الحل لكل برنامج أكاديمي',
    'complaintsDash.perProgram': 'نسبة الحل لكل برنامج:',
    'complaintsDash.noDataToShow': 'لا توجد بيانات للعرض',
    'complaintsDash.complaint': 'شكوى',
    'complaintsDash.count': 'العدد',

    // Complaint Statistics
    'complaintStats.title': 'تقارير إحصائيات الشكاوى',
    'complaintStats.subtitle': 'إحصائيات شاملة للشكاوى مع إمكانية التصفية والتصدير',
    'complaintStats.program': 'البرنامج:',
    'complaintStats.allPrograms': 'جميع البرامج',
    'complaintStats.resolutionRate': 'نسبة الحل',
    'complaintStats.byType': 'توزيع الشكاوى حسب النوع',
    'complaintStats.byStatus': 'توزيع الشكاوى حسب الحالة',
    'complaintStats.byMonth': 'الشكاوى حسب الشهر',

    // Report Dashboard
    'reportDash.totalResponses': 'إجمالي الاستجابات',
    'reportDash.overallMean': 'المتوسط العام',
    'reportDash.outOf5': 'من 5.0',
    'reportDash.questionsCount': 'عدد الأسئلة',
    'reportDash.textComments': 'التعليقات النصية',
    'reportDash.analyzeEachQuestion': 'تحليل كل سؤال',
    'reportDash.question': 'سؤال',
    'reportDash.likert': 'مقياس ليكرت',
    'reportDash.ratingType': 'تقييم',
    'reportDash.mcqType': 'اختيار متعدد',
    'reportDash.textType': 'نص حر',
    'reportDash.responseDistribution': 'توزيع الاستجابات',
    'reportDash.percentages': 'النسب المئوية',
    'reportDash.mean': 'المتوسط',
    'reportDash.stdDev': 'الانحراف المعياري',
    'reportDash.responseRate': 'معدل الاستجابة',
    'reportDash.responseDetails': 'تفاصيل الاستجابات',
    'reportDash.choiceDistribution': 'توزيع الاختيارات',
    'reportDash.textResponses': 'الردود النصية',
    'reportDash.noTextResponses': 'لا توجد ردود نصية',
    'reportDash.moreResponses': 'استجابة أخرى',
    'reportDash.overallSummary': 'الملخص العام للتقييمات',
    'reportDash.overallSummaryDesc': 'متوسط جميع أسئلة مقياس ليكرت والتقييم',
    'reportDash.excellent': 'ممتاز',
    'reportDash.veryGood': 'جيد جداً',
    'reportDash.average': 'متوسط',
    'reportDash.poor': 'ضعيف',
    'reportDash.veryPoor': 'ضعيف جداً',
    'reportDash.response': 'استجابة',

    // Survey Preview
    'preview.title': 'معاينة الاستبيان',
    'preview.print': 'طباعة',
    'preview.anonymous': 'استبيان مجهول',
    'preview.named': 'استبيان بالاسم',
    'preview.thankYou': 'شكراً لمشاركتك في هذا الاستبيان',
    'preview.helpImprove': 'إجاباتك ستساعدنا في تحسين جودة خدماتنا',

    // Survey Distribution
    'distribution.surveyInfo': 'معلومات الاستبيان',
    'distribution.surveyPeriod': 'فترة الاستبيان',
    'distribution.notSpecified': 'غير محدد',
    'distribution.responseCount': 'عدد الاستجابات',
    'distribution.completionRate': 'معدل الإكمال',
    'distribution.directLink': 'الرابط المباشر',
    'distribution.directLinkTitle': 'الرابط المباشر للاستبيان',
    'distribution.qrCode': 'رمز QR',
    'distribution.qrTitle': 'رمز QR للاستبيان',
    'distribution.email': 'البريد الإلكتروني',
    'distribution.emailTitle': 'قالب البريد الإلكتروني',
    'distribution.social': 'وسائل التواصل',
    'distribution.socialTitle': 'وسائل التواصل الاجتماعي',

    // Survey Templates  
    'templates.allTemplates': 'جميع القوالب',
    'templates.courseEval': 'تقييم المقررات',
    'templates.satisfaction': 'رضا الطلاب',
    'templates.quality': 'جودة التعليم',
    'templates.noTemplates': 'لا توجد قوالب',
    'templates.noTemplatesInCategory': 'لا توجد قوالب في هذه الفئة',
    'templates.noTemplatesAvailable': 'لا توجد قوالب متاحة حالياً',

    // Complaints page specific
    'complaints.newLabel': 'جديدة',
    'complaints.inAction': 'قيد الإجراء',
    'complaints.complaintLink': 'رابط تقديم الشكوى',
    'complaints.qrCode': 'رمز QR للشكاوى',
    'complaints.statistics': 'الإحصائيات',
    'complaints.dashboard': 'لوحة التحكم',
    'complaints.list': 'القائمة',
    'complaints.notSpecified': 'غير محدد',
    'complaints.resolutionNotes': 'ملاحظات الحل',
    'complaints.enterResolutionNotes': 'أدخل ملاحظات الحل...',
    'complaints.confirmResolve': 'تأكيد الحل',
    'complaints.allPrograms': 'جميع البرامج',
    'complaints.allStatuses': 'جميع الحالات',
    'complaints.deleteConfirm': 'هل أنت متأكد من حذف هذه الشكوى؟',

    // Auth

    'auth.login': 'تسجيل الدخول',
    'auth.logout': 'تسجيل الخروج',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.register': 'إنشاء حساب',
    'auth.fullName': 'الاسم الكامل',
    'auth.program': 'البرنامج',
    'auth.selectProgram': 'اختر البرنامج',
    'auth.systemTitle': 'منظومة الاستبيانات الذكية',
    'auth.systemSubtitle': 'كلية العلوم الإنسانية والاجتماعية',
    'auth.loggingIn': 'جاري الدخول...',
    'auth.enter': 'دخول',
    'auth.creating': 'جاري الإنشاء...',
    'auth.createAccount': 'إنشاء حساب',
    
    // Common
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.add': 'إضافة',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    'common.loading': 'جاري التحميل...',
    'common.noData': 'لا توجد بيانات',
    'common.confirm': 'تأكيد',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.close': 'إغلاق',
    'common.actions': 'الإجراءات',
    'common.name': 'الاسم',
    'common.email': 'البريد الإلكتروني',
    'common.date': 'التاريخ',
    'common.program': 'البرنامج',
    'common.semester': 'الفصل الدراسي',
    'common.academicYear': 'السنة الأكاديمية',
    'common.back': 'رجوع',
    'common.copied': 'تم النسخ',
    'common.error': 'خطأ',
    'common.success': 'نجاح',
    'common.updated': 'تم التحديث',
    'common.deleted': 'تم الحذف',
    'common.saved': 'تم الحفظ',
    'common.unauthorized': 'غير مصرح',
    'common.adminOnly': 'هذه الصفحة متاحة للمديرين فقط',
    
    // Index/Landing
    'index.title': 'نظام إدارة الاستبيانات',
    'index.subtitle': 'منصة متكاملة لإدارة الاستبيانات والشكاوى',
    'index.getStarted': 'ابدأ الآن',
    'index.login': 'تسجيل الدخول',
    'index.features': 'المميزات',
    'index.feature1.title': 'استبيانات ذكية',
    'index.feature1.desc': 'إنشاء وإدارة استبيانات متنوعة بسهولة',
    'index.feature2.title': 'تحليلات متقدمة',
    'index.feature2.desc': 'تقارير وتحليلات تفصيلية للبيانات',
    'index.feature3.title': 'إدارة الشكاوى',
    'index.feature3.desc': 'نظام متكامل لإدارة ومتابعة الشكاوى',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.surveys': 'Surveys',
    'nav.complaints': 'Complaints',
    'nav.recommendations': 'Recommendations',
    'nav.archives': 'Archives',
    'nav.comparison': 'Program Comparison',
    'nav.users': 'Users',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.home': 'Home',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome to Survey Management System',
    'dashboard.welcomeUser': 'Welcome',
    'dashboard.systemTitle': 'Smart Survey System',
    'dashboard.totalSurveys': 'Total Surveys',
    'dashboard.activeSurveys': 'Active Surveys',
    'dashboard.totalResponses': 'Total Responses',
    'dashboard.responseRate': 'Response Rate',
    'dashboard.readyReports': 'Ready Reports',
    'dashboard.pendingComplaints': 'Pending Complaints',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.recentSurveys': 'Recent Surveys',
    'dashboard.recentSurveysDesc': 'Active surveys and response status',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.createSurvey': 'Create New Survey',
    'dashboard.newSurvey': 'New Survey',
    'dashboard.viewReports': 'View Reports',
    'dashboard.viewReport': 'View Report',
    'dashboard.manageComplaints': 'Manage Complaints',
    'dashboard.manageSurveys': 'Manage Surveys',
    'dashboard.noSurveys': 'No surveys currently',
    'dashboard.viewAllSurveys': 'View All Surveys',
    'dashboard.followRecommendations': 'Follow Recommendations',
    'dashboard.semesterArchive': 'Semester Archive',
    'dashboard.manageUsers': 'Manage Users',
    'dashboard.systemSettings': 'System Settings',
    'dashboard.response': 'response',
    
    // Surveys
    'surveys.title': 'Survey Management',
    'surveys.subtitle': 'View and manage surveys and templates',
    'surveys.create': 'Create Survey',
    'surveys.edit': 'Edit',
    'surveys.delete': 'Delete',
    'surveys.view': 'View',
    'surveys.status': 'Status',
    'surveys.responses': 'Responses',
    'surveys.actions': 'Actions',
    'surveys.draft': 'Draft',
    'surveys.active': 'Active',
    'surveys.closed': 'Closed',
    'surveys.noSurveys': 'No surveys found',
    'surveys.createFirst': 'Create First Survey',
    'surveys.newSurvey': 'New Survey',
    'surveys.templates': 'Templates',
    'surveys.updateQR': 'Update QR Codes',
    'surveys.searchPlaceholder': 'Search surveys...',
    'surveys.activate': 'Activate',
    'surveys.deactivate': 'Deactivate',
    'surveys.link': 'Link',
    'surveys.report': 'Report',
    'surveys.program': 'Program',
    'surveys.noTemplates': 'No saved templates',
    'surveys.createAndSaveTemplate': 'Create survey and save as template',
    'surveys.public': 'Public',
    'surveys.useTemplate': 'Use',
    
    // Complaints
    'complaints.title': 'Complaints Management',
    'complaints.subtitle': 'Track and process student and staff complaints',
    'complaints.submit': 'Submit Complaint',
    'complaints.submitNew': 'New Complaint',
    'complaints.status': 'Status',
    'complaints.pending': 'Under Review',
    'complaints.inProgress': 'In Progress',
    'complaints.resolved': 'Resolved',
    'complaints.closed': 'Closed',
    'complaints.subject': 'Subject',
    'complaints.description': 'Description',
    'complaints.type': 'Type',
    'complaints.date': 'Date',
    'complaints.total': 'Total Complaints',
    'complaints.submitComplaint': 'Submit Complaint',
    'complaints.submitTitle': 'Submit a Complaint',
    'complaints.submitSubtitle': 'We are here to listen to your feedback and complaints',
    'complaints.formTitle': 'Complaint Form',
    'complaints.formSubtitle': 'Please fill in all required fields (*)',
    'complaints.confidentialNote': 'All complaints are handled confidentially. Please provide accurate information to help us resolve the issue as quickly as possible.',
    'complaints.personalInfo': 'Personal Information',
    'complaints.fullName': 'Full Name',
    'complaints.email': 'Email',
    'complaints.academicId': 'Academic / Employee ID',
    'complaints.complainantType': 'Complainant Type',
    'complaints.student': 'Student',
    'complaints.faculty': 'Faculty Member',
    'complaints.staff': 'Staff',
    'complaints.other': 'Other',
    'complaints.program': 'Academic Program',
    'complaints.selectProgram': 'Select Program (optional)',
    'complaints.semester': 'Semester',
    'complaints.selectSemester': 'Select Semester',
    'complaints.fall': 'Fall',
    'complaints.spring': 'Spring',
    'complaints.summer': 'Summer',
    'complaints.academicYear': 'Academic Year',
    'complaints.details': 'Complaint Details',
    'complaints.category': 'Complaint Type',
    'complaints.academic': 'Academic',
    'complaints.administrative': 'Administrative',
    'complaints.technical': 'Technical',
    'complaints.complaintSubject': 'Complaint Subject',
    'complaints.complaintDetails': 'Complaint Details',
    'complaints.attachments': 'Attachments (optional)',
    'complaints.uploadFiles': 'Click to upload files (PDF, images, documents)',
    'complaints.filesSelected': 'file(s) selected',
    'complaints.submitBtn': 'Submit Complaint',
    'complaints.cancel': 'Cancel',
    'complaints.submitting': 'Submitting...',
    
    // Recommendations
    'recommendations.title': 'Recommendations Management',
    'recommendations.subtitle': 'Track and implement improvement recommendations',
    'recommendations.add': 'Add Recommendation',
    'recommendations.edit': 'Edit',
    'recommendations.priority': 'Priority',
    'recommendations.status': 'Status',
    'recommendations.high': 'High',
    'recommendations.medium': 'Medium',
    'recommendations.low': 'Low',
    'recommendations.total': 'Total Recommendations',
    'recommendations.completed': 'Completed',
    'recommendations.inProgress': 'In Progress',
    'recommendations.pending': 'Pending',
    'recommendations.completionRate': 'Completion Rate',
    'recommendations.list': 'Recommendations List',
    'recommendations.date': 'Date',
    'recommendations.titleLabel': 'Title',
    'recommendations.programLabel': 'Program',
    'recommendations.source': 'Source',
    'recommendations.actions': 'Actions',
    'recommendations.addNew': 'Add New Recommendation',
    'recommendations.editTitle': 'Edit Recommendation',
    'recommendations.addDescription': 'Add a new improvement recommendation',
    'recommendations.editDescription': 'Edit recommendation details',
    'recommendations.recommendationTitle': 'Recommendation Title',
    'recommendations.details': 'Details',
    'recommendations.selectProgram': 'Select Program',
    'recommendations.survey': 'Survey',
    'recommendations.complaint': 'Complaint',
    'recommendations.manual': 'Manual',
    'recommendations.selectSemester': 'Select Semester',
    'recommendations.first': 'First',
    'recommendations.second': 'Second',
    'recommendations.summerSem': 'Summer',
    'recommendations.saving': 'Saving...',
    'recommendations.update': 'Update',
    
    // Reports
    'reports.title': 'Reports & Analytics',
    'reports.generate': 'Generate Report',
    'reports.download': 'Download',
    'reports.exportPdf': 'Export PDF',
    'reports.exportExcel': 'Export Excel',
    'reports.reanalyze': 'Re-analyze',
    'reports.analyzing': 'Analyzing...',
    'reports.deleteReport': 'Delete Report',
    'reports.noReport': 'No Report',
    'reports.noReportDesc': 'No report has been created for this survey yet',
    'reports.createWithAI': 'Create Report with AI',
    'reports.creating': 'Creating report...',
    'reports.backToSurveys': 'Back to Surveys',
    'reports.metadata': 'Report Data',
    'reports.metadataDesc': 'Set semester and report status',
    'reports.semester': 'Semester',
    'reports.academicYear': 'Academic Year',
    'reports.status': 'Report Status',
    'reports.responding': 'Under Response',
    'reports.completed': 'Completed',
    'reports.noResponse': 'No Response',
    'reports.cancelled': 'Cancelled',
    'reports.saveMetadata': 'Save Report Data',
    'reports.totalResponses': 'Total Responses',
    'reports.response': 'response',
    'reports.questionsCount': 'Number of Questions',
    'reports.question': 'question',
    'reports.overallMean': 'Overall Mean',
    'reports.outOf5': 'out of 5.0',
    'reports.stdDev': 'Standard Deviation',
    'reports.consistency': 'Consistency',
    'reports.aiSummary': 'AI Executive Summary',
    'reports.aiSummaryDesc': 'Automated analysis of results and recommendations',
    'reports.editContent': 'Edit Content',
    'reports.executiveSummary': 'Executive Summary:',
    'reports.recommendationsLabel': 'Recommendations:',
    'reports.questionDetails': 'Results by Question',
    'reports.questionDetailsDesc': 'Detailed statistics for each question',
    'reports.answersCount': 'Answer Count',
    'reports.mean': 'Mean',
    'reports.deviation': 'Deviation',
    
    // Archives
    'archives.title': 'Semester Archive',
    'archives.subtitle': 'Manage and organize semester archives for surveys and reports',
    'archives.view': 'View Archive',
    'archives.restore': 'Restore',
    'archives.archiveNew': 'Archive New Item',
    'archives.totalItems': 'Total Items',
    'archives.surveys': 'Surveys',
    'archives.reports': 'Reports',
    'archives.complaints': 'Complaints',
    'archives.frozen': 'Frozen',
    'archives.listView': 'List View',
    'archives.timelineView': 'Timeline View',
    'archives.searchPlaceholder': 'Search archive...',
    'archives.allTypes': 'All Types',
    'archives.allSemesters': 'All Semesters',
    'archives.allYears': 'All Years',
    'archives.recommendations': 'Recommendations',
    'archives.survey': 'Survey',
    'archives.report': 'Report',
    'archives.complaint': 'Complaint',
    'archives.recommendation': 'Recommendation',
    'archives.archivedOn': 'Archived on',
    'archives.by': 'by',
    'archives.system': 'System',
    'archives.noItems': 'No archived items',
    'archives.noMatchingItems': 'No items match the search criteria',
    'archives.noArchivedYet': 'No items have been archived yet',
    'archives.academicYear': 'Academic Year',
    
    // Users
    'users.title': 'User Management',
    'users.subtitle': 'Manage users and permissions',
    'users.add': 'Add User',
    'users.role': 'Role',
    'users.admin': 'System Admin',
    'users.coordinator': 'Program Coordinator',
    'users.programManager': 'Program Manager',
    'users.dean': 'Dean',
    'users.user': 'User',
    'users.usersList': 'Users List',
    'users.name': 'Name',
    'users.email': 'Email',
    'users.program': 'Program',
    'users.noProgram': 'None',
    'users.notSet': 'Not set',
    'users.changeRole': 'Change Role',
    'users.selectProgram': 'Select Program',
    'users.adminDesc': 'Full permissions on everything in the system',
    'users.coordinatorDesc': 'Create surveys + full management of their program',
    'users.programManagerDesc': 'View results only for their program',
    'users.deanDesc': 'View results of all programs',
    
    // Settings
    'settings.title': 'System Settings',
    'settings.subtitle': 'Manage general system settings',
    'settings.general': 'General',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security',
    'settings.collegeLogo': 'College Logo',
    'settings.logoUrl': 'Logo URL',
    'settings.save': 'Save',
    'settings.saving': 'Saving...',
    'settings.logoDesc': 'Enter the college logo URL. It will appear in all exported reports.',
    'settings.logoPreview': 'Logo Preview',
    'settings.tips': 'Tips:',
    'settings.tip1': 'Use an image with a transparent background (PNG) for the best result',
    'settings.tip2': 'Recommended size: 200x200 pixels or larger',
    'settings.tip3': 'Make sure the link works and is accessible',
    
    // Comparison
    'comparison.title': 'Program Comparison',
    'comparison.subtitle': 'Compare performance of different academic programs',
    'comparison.select': 'Select programs to compare',
    'comparison.academicYear': 'Academic Year',
    'comparison.semester': 'Semester',
    'comparison.allSemesters': 'All Semesters',
    'comparison.selectPrograms': 'Select Programs (2+)',
    'comparison.addProgram': 'Add Program',
    'comparison.compare': 'Compare',
    'comparison.overallPerformance': 'Overall Performance',
    'comparison.noData': 'No data for comparison',
    'comparison.selectAtLeast2': 'Please select at least two programs',
    'comparison.selectYear': 'Please select academic year',
    'comparison.bestProgram': 'Best Program',
    'comparison.satisfactionRate': 'Satisfaction Rate',
    'comparison.notAvailable': 'N/A',

    // Survey Designer
    'designer.title': 'Survey Designer',
    'designer.editTitle': 'Edit Survey',
    'designer.surveyTitle': 'Survey Title',
    'designer.surveyDescription': 'Survey Description',
    'designer.program': 'Program',
    'designer.selectProgram': 'Select Program',
    'designer.anonymous': 'Anonymous Survey',
    'designer.startDate': 'Start Date',
    'designer.endDate': 'End Date',
    'designer.semester': 'Semester',
    'designer.academicYear': 'Academic Year',
    'designer.targetEnrollment': 'Target Enrollment',
    'designer.addQuestion': 'Add Question',
    'designer.addSection': 'Add Section',
    'designer.save': 'Save Survey',
    'designer.saving': 'Saving...',
    'designer.saveTemplate': 'Save as Template',
    'designer.preview': 'Preview',
    'designer.design': 'Design',
    'designer.templates': 'Templates',
    'designer.questionText': 'Question Text',
    'designer.sectionTitle': 'Section Title',
    'designer.questionType': 'Question Type',
    'designer.required': 'Required',
    'designer.options': 'Options',
    'designer.addOption': 'Add Option',
    'designer.duplicate': 'Duplicate',
    'designer.importExport': 'Import/Export',
    'designer.importJSON': 'Import JSON',
    'designer.importCSV': 'Import CSV',
    'designer.exportJSON': 'Export JSON',
    'designer.exportCSV': 'Export CSV',
    'designer.likert': 'Likert Scale',
    'designer.likertDesc': '1-5 scale for agreement',
    'designer.text': 'Open Text',
    'designer.textDesc': 'Free text response',
    'designer.mcq': 'Multiple Choice',
    'designer.mcqDesc': 'Choose from options',
    'designer.rating': 'Rating/Ranking',
    'designer.ratingDesc': 'Star rating or ranking',
    'designer.section': 'Section Header',
    'designer.sectionDesc': 'Header for grouping questions',
    'designer.suggestWithAI': 'Suggest with AI',
    'designer.existingResponses': 'Existing Responses',
    'designer.existingResponsesWarning': 'This survey has responses. Modifying questions may affect data.',
    'designer.enterTitleAndProgram': 'Please enter survey title and select program',
    'designer.enterAllQuestions': 'Please enter text for all questions',
    'designer.surveyUpdated': 'Survey updated successfully',
    'designer.surveySaved': 'Survey saved successfully',
    'designer.createCustom': 'Create Custom Survey',
    'designer.createCustomDesc': 'Start from scratch and create survey as needed',
    'designer.useTemplate': 'Use Template',
    'designer.questions': 'questions',

    // Take Survey
    'takeSurvey.loading': 'Loading survey...',
    'takeSurvey.notFound': 'Survey Not Found',
    'takeSurvey.notFoundDesc': 'The requested survey was not found',
    'takeSurvey.inactive': 'Survey Not Available',
    'takeSurvey.inactiveDesc': 'This survey is currently inactive. Please contact the program coordinator.',
    'takeSurvey.stronglyDisagree': 'Strongly Disagree',
    'takeSurvey.disagree': 'Disagree',
    'takeSurvey.neutral': 'Neutral',
    'takeSurvey.agree': 'Agree',
    'takeSurvey.stronglyAgree': 'Strongly Agree',
    'takeSurvey.next': 'Next',
    'takeSurvey.previous': 'Previous',
    'takeSurvey.submit': 'Submit',
    'takeSurvey.submitting': 'Submitting...',
    'takeSurvey.questionRequired': 'This question is required',
    'takeSurvey.requiredQuestions': 'Required Questions',
    'takeSurvey.remainingQuestions': 'remaining question(s)',
    'takeSurvey.submitted': 'Survey Submitted',
    'takeSurvey.thankYou': 'Thank you for participating',
    'takeSurvey.selectRating': 'Select Rating',
    'takeSurvey.starsOf5': 'stars out of 5',
    'takeSurvey.answerPlaceholder': 'Enter your answer here...',
    'takeSurvey.questionOf': 'Question',
    'takeSurvey.of': 'of',
    'takeSurvey.anonymous': 'Anonymous Survey',
    'takeSurvey.named': 'Named Survey',

    // Survey Complete
    'surveyComplete.title': 'Thank You!',
    'surveyComplete.description': 'Your responses have been submitted successfully. We appreciate your time and contribution.',
    'surveyComplete.retake': 'Take Survey Again',

    // Complaint Submitted
    'complaintSubmitted.title': 'Complaint Submitted Successfully',
    'complaintSubmitted.description': 'Thank you. Your complaint has been received and will be reviewed shortly.',
    'complaintSubmitted.trackingNote': 'You can track your complaint status through the system.',
    'complaintSubmitted.backHome': 'Back to Home',
    'complaintSubmitted.submitAnother': 'Submit Another Complaint',

    // Academic Calendar
    'calendar.title': 'Academic Calendar',
    'calendar.subtitle': 'Manage semesters and academic years',
    'calendar.addSemester': 'Add Semester',
    'calendar.addNew': 'Add New Semester',
    'calendar.editSemester': 'Edit Semester',
    'calendar.semesters': 'Semesters',
    'calendar.semestersDesc': 'List of all registered semesters and academic years',
    'calendar.academicYear': 'Academic Year',
    'calendar.selectYear': 'Select Academic Year',
    'calendar.semester': 'Semester',
    'calendar.selectSemester': 'Select Semester',
    'calendar.startDate': 'Start Date',
    'calendar.endDate': 'End Date',
    'calendar.status': 'Status',
    'calendar.actions': 'Actions',
    'calendar.current': 'Current Semester',
    'calendar.inactive': 'Inactive',
    'calendar.setCurrent': 'Set as Current',
    'calendar.noSemesters': 'No semesters registered',
    'calendar.addToStart': 'Add a new semester to start',
    'calendar.first': 'First Semester',
    'calendar.second': 'Second Semester',
    'calendar.summer': 'Summer Semester',
    'calendar.fillAllFields': 'Please fill all fields',
    'calendar.duplicateError': 'This semester already exists for this academic year',
    'calendar.added': 'Added',
    'calendar.addSuccess': 'Semester added successfully',
    'calendar.updateSuccess': 'Semester updated successfully',
    'calendar.deleteSuccess': 'Semester deleted successfully',
    'calendar.setCurrentSuccess': 'Current semester set successfully',
    'calendar.confirmDelete': 'Confirm Delete Semester',
    'calendar.confirmDeleteDesc': 'Are you sure you want to delete this semester? This action cannot be undone.',

    // Not Found
    'notFound.title': '404',
    'notFound.message': 'Page Not Found',
    'notFound.back': 'Back to Home',

    // QR Code Dialog
    'qr.title': 'QR Code',
    'qr.description': 'Scan this code for direct access to the survey',
    'qr.download': 'Download Code',
    'qr.copyLink': 'Copy Link',
    'qr.downloaded': 'Downloaded',
    'qr.downloadSuccess': 'QR Code downloaded successfully',

    // Add User Dialog
    'addUser.title': 'Add New User',
    'addUser.description': 'Add a new user to the system. They will be asked to change password on first login.',
    'addUser.fullName': 'Full Name',
    'addUser.email': 'Email',
    'addUser.password': 'Temporary Password',
    'addUser.defaultPassword': 'Default password: 123456789',
    'addUser.adding': 'Adding...',
    'addUser.add': 'Add User',
    'addUser.success': 'User Added',
    'addUser.fillRequired': 'Please fill all required fields',

    // User Roles Dialog
    'roles.title': 'Manage Permissions',
    'roles.description': 'You can add multiple permissions for the user on different programs',
    'roles.noRoles': 'No permissions assigned to this user',
    'roles.addNew': 'Add New Permission',
    'roles.selectRole': 'Select Role',
    'roles.allPrograms': 'Full access to all programs',
    'roles.viewAll': 'View all programs',
    'roles.summary': 'Permissions Summary:',
    'roles.saveRoles': 'Save Permissions',
    'roles.saved': 'User permissions updated successfully',
    'roles.managePermissions': 'Manage Permissions',
    'roles.noPermissions': 'No permissions',
    'roles.faculty': 'Faculty Member',

    // Reset Password Dialog
    'resetPassword.title': 'Reset Password',
    'resetPassword.confirm': 'Are you sure you want to reset password for user',
    'resetPassword.newPassword': 'New Password:',
    'resetPassword.note': 'User will be asked to change password on next login.',
    'resetPassword.resetting': 'Resetting...',
    'resetPassword.reset': 'Reset Password',
    'resetPassword.success': 'Password Reset Successfully',

    // Delete User Dialog
    'deleteUser.title': 'Confirm Delete User',
    'deleteUser.confirm': 'Are you sure you want to delete user',
    'deleteUser.warning': 'This action cannot be undone and will delete all user data.',
    'deleteUser.deleting': 'Deleting...',
    'deleteUser.delete': 'Delete User',

    // PDF Preview
    'pdfPreview.title': 'Report Preview',
    'pdfPreview.generating': 'Generating report...',
    'pdfPreview.pleaseWait': 'Please wait',
    'pdfPreview.noFile': 'No file to preview',
    'pdfPreview.download': 'Download PDF',

    // Survey Analytics
    'analytics.title': 'Survey Analytics',
    'analytics.subtitle': 'Comprehensive overview of survey results',
    'analytics.totalResponses': 'Total Responses',
    'analytics.completionRate': 'Completion Rate',
    'analytics.avgTime': 'Avg Time',
    'analytics.noData': 'No Data',
    'analytics.noDataDesc': 'Not enough responses to display analytics',
    'analytics.filter': 'Filter',
    'analytics.all': 'All',
    'analytics.last7days': 'Last 7 days',
    'analytics.last30days': 'Last 30 days',
    'analytics.last90days': 'Last 90 days',
    'analytics.timePeriod': 'Time Period',
    'analytics.exportReport': 'Export Report',
    'analytics.exporting': 'Exporting...',
    'analytics.exportFormat': 'Export Format',
    'analytics.exportSuccess': 'Exported',
    'analytics.exportedPDF': 'Report exported successfully as PDF',
    'analytics.exportedExcel': 'Report exported successfully as Excel',

    // Complaints Dashboard
    'complaintsDash.title': 'Complaints Dashboard',
    'complaintsDash.allPrograms': 'Overview of all college complaints',
    'complaintsDash.myProgram': 'Complaints for your academic program',
    'complaintsDash.filterByProgram': 'Filter by Program:',
    'complaintsDash.totalComplaints': 'Total Complaints',
    'complaintsDash.newComplaints': 'New Complaints',
    'complaintsDash.inAction': 'In Progress',
    'complaintsDash.resolved': 'Resolved',
    'complaintsDash.resolutionRate': 'Resolution Rate',
    'complaintsDash.resolvedOf': '{0} of {1} complaints resolved',
    'complaintsDash.byStatus': 'Complaints by Status',
    'complaintsDash.byComplainant': 'Complaints by Complainant Type',
    'complaintsDash.programComparison': 'Program Performance Comparison',
    'complaintsDash.programComparisonDesc': 'Number of complaints and resolution rate per program',
    'complaintsDash.perProgram': 'Resolution rate per program:',
    'complaintsDash.noDataToShow': 'No data to display',
    'complaintsDash.complaint': 'Complaint',
    'complaintsDash.count': 'Count',

    // Complaint Statistics
    'complaintStats.title': 'Complaints Statistics Reports',
    'complaintStats.subtitle': 'Comprehensive statistics for complaints with filtering and export',
    'complaintStats.program': 'Program:',
    'complaintStats.allPrograms': 'All Programs',
    'complaintStats.resolutionRate': 'Resolution Rate',
    'complaintStats.byType': 'Complaints by Type',
    'complaintStats.byStatus': 'Complaints by Status',
    'complaintStats.byMonth': 'Complaints by Month',

    // Report Dashboard
    'reportDash.totalResponses': 'Total Responses',
    'reportDash.overallMean': 'Overall Mean',
    'reportDash.outOf5': 'out of 5.0',
    'reportDash.questionsCount': 'Question Count',
    'reportDash.textComments': 'Text Comments',
    'reportDash.analyzeEachQuestion': 'Analyze Each Question',
    'reportDash.question': 'Question',
    'reportDash.likert': 'Likert Scale',
    'reportDash.ratingType': 'Rating',
    'reportDash.mcqType': 'Multiple Choice',
    'reportDash.textType': 'Free Text',
    'reportDash.responseDistribution': 'Response Distribution',
    'reportDash.percentages': 'Percentages',
    'reportDash.mean': 'Mean',
    'reportDash.stdDev': 'Std Dev',
    'reportDash.responseRate': 'Response Rate',
    'reportDash.responseDetails': 'Response Details',
    'reportDash.choiceDistribution': 'Choice Distribution',
    'reportDash.textResponses': 'Text Responses',
    'reportDash.noTextResponses': 'No text responses',
    'reportDash.moreResponses': 'more responses',
    'reportDash.overallSummary': 'Overall Summary',
    'reportDash.overallSummaryDesc': 'Average of all Likert and rating questions',
    'reportDash.excellent': 'Excellent',
    'reportDash.veryGood': 'Very Good',
    'reportDash.average': 'Average',
    'reportDash.poor': 'Poor',
    'reportDash.veryPoor': 'Very Poor',
    'reportDash.response': 'response',

    // Survey Preview
    'preview.title': 'Survey Preview',
    'preview.print': 'Print',
    'preview.anonymous': 'Anonymous Survey',
    'preview.named': 'Named Survey',
    'preview.thankYou': 'Thank you for participating',
    'preview.helpImprove': 'Your answers will help us improve our services',

    // Survey Distribution
    'distribution.surveyInfo': 'Survey Info',
    'distribution.surveyPeriod': 'Survey Period',
    'distribution.notSpecified': 'Not specified',
    'distribution.responseCount': 'Response Count',
    'distribution.completionRate': 'Completion Rate',
    'distribution.directLink': 'Direct Link',
    'distribution.directLinkTitle': 'Direct Survey Link',
    'distribution.qrCode': 'QR Code',
    'distribution.qrTitle': 'Survey QR Code',
    'distribution.email': 'Email',
    'distribution.emailTitle': 'Email Template',
    'distribution.social': 'Social Media',
    'distribution.socialTitle': 'Social Media Sharing',

    // Survey Templates  
    'templates.allTemplates': 'All Templates',
    'templates.courseEval': 'Course Evaluation',
    'templates.satisfaction': 'Student Satisfaction',
    'templates.quality': 'Education Quality',
    'templates.noTemplates': 'No Templates',
    'templates.noTemplatesInCategory': 'No templates in this category',
    'templates.noTemplatesAvailable': 'No templates available currently',

    // Complaints page specific
    'complaints.newLabel': 'New',
    'complaints.inAction': 'In Progress',
    'complaints.complaintLink': 'Complaint Link',
    'complaints.qrCode': 'Complaint QR Code',
    'complaints.statistics': 'Statistics',
    'complaints.dashboard': 'Dashboard',
    'complaints.list': 'List',
    'complaints.notSpecified': 'Not Specified',
    'complaints.resolutionNotes': 'Resolution Notes',
    'complaints.enterResolutionNotes': 'Enter resolution notes...',
    'complaints.confirmResolve': 'Confirm Resolve',
    'complaints.allPrograms': 'All Programs',
    'complaints.allStatuses': 'All Statuses',
    'complaints.deleteConfirm': 'Are you sure you want to delete this complaint?',

    // Auth
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.register': 'Register',
    'auth.fullName': 'Full Name',
    'auth.program': 'Program',
    'auth.selectProgram': 'Select Program',
    'auth.systemTitle': 'Smart Survey System',
    'auth.systemSubtitle': 'College of Humanities and Social Sciences',
    'auth.loggingIn': 'Logging in...',
    'auth.enter': 'Login',
    'auth.creating': 'Creating...',
    'auth.createAccount': 'Create Account',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.loading': 'Loading...',
    'common.noData': 'No data available',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.close': 'Close',
    'common.actions': 'Actions',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.date': 'Date',
    'common.program': 'Program',
    'common.semester': 'Semester',
    'common.academicYear': 'Academic Year',
    'common.back': 'Back',
    'common.copied': 'Copied',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.updated': 'Updated',
    'common.deleted': 'Deleted',
    'common.saved': 'Saved',
    'common.unauthorized': 'Unauthorized',
    'common.adminOnly': 'This page is available to admins only',
    
    // Index/Landing
    'index.title': 'Survey Management System',
    'index.subtitle': 'Integrated platform for managing surveys and complaints',
    'index.getStarted': 'Get Started',
    'index.login': 'Login',
    'index.features': 'Features',
    'index.feature1.title': 'Smart Surveys',
    'index.feature1.desc': 'Create and manage various surveys easily',
    'index.feature2.title': 'Advanced Analytics',
    'index.feature2.desc': 'Detailed reports and data analytics',
    'index.feature3.title': 'Complaint Management',
    'index.feature3.desc': 'Integrated system for managing and tracking complaints',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'ar';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
